FROM openjdk:11-jre-slim
LABEL maintainer="Aaron Coburn <acoburn@apache.org>"

ADD build/distributions/trellis-*.tar /opt
RUN mv /opt/trellis-* /opt/trellis
COPY src/main/docker/command.sh /
RUN chmod +x /command.sh

CMD ["/command.sh"]
